
// Emoji map for different item categories
export const EMOJI_MAP: Record<string, string> = {
  "fruta": "🍎",
  "manzana": "🍎",
  "banana": "🍌",
  "plátano": "🍌",
  "naranja": "🍊",
  "limón": "🍋",
  "pera": "🍐",
  "uva": "🍇",
  "sandía": "🍉",
  "fresa": "🍓",
  "piña": "🍍",
  "cebolla": "🧅",
  "ajo": "🧄",
  "verdura": "🥦",
  "lechuga": "🥬",
  "zanahoria": "🥕",
  "brócoli": "🥦",
  "tomate": "🍅",
  "patata": "🥔",
  "papa": "🥔",
  "aguacate": "🥑",
  "maíz": "🌽",
  "carne": "🥩",
  "pollo": "🍗",
  "pescado": "🐟",
  "pan": "🍞",
  "pasta": "🍝",
  "arroz": "🍚",
  "huevo": "🥚",
  "leche": "🥛",
  "queso": "🧀",
  "yogur": "🥛",
  "mantequilla": "🧈",
  "aceite": "🫒",
  "sal": "🧂",
  "azúcar": "🧂",
  "chocolate": "🍫",
  "galletas": "🍪",
  "pastel": "🍰",
  "helado": "🍦",
  "pizza": "🍕",
  "hamburguesa": "🍔",
  "agua": "💧",
  "cerveza": "🍺",
  "vino": "🍷",
  "café": "☕",
  "té": "🍵",
  "zumo": "🧃",
  "jugo": "🧃",
  "refresco": "🥤",
  "papel": "🧻",
  "detergente": "🧼",
  "jabón": "🧼",
  "champú": "🧴",
  "pasta dental": "🪥",
  "cepillo dental": "🪥",
  "medicamento": "💊",
  "medicina": "💊",
  "pañales": "👶",
  "default": "📦"
};

// Common shopping items for autocomplete
export const COMMON_SHOPPING_ITEMS = [
  "agua", "aceite", "aceitunas", "ajo", "arroz", "atún", "azúcar",
  "banana", "carne", "café", "cebolla", "cereales", "cerveza",
  "champú", "chocolate", "detergente", "fruta", "galletas", "huevos",
  "jabón", "jamón", "jugo", "leche", "lechuga", "limón", "manzana",
  "naranja", "pan", "papel higiénico", "pasta", "pasta dental",
  "patatas", "pescado", "piña", "plátano", "pollo", "queso", "sal", 
  "salsa", "sandía", "té", "tomate", "uva", "verduras", "vino",
  "yogur", "zanahoria", "zumo"
];

// Known words for spellcheck
export const KNOWN_WORDS_FOR_SPELLCHECK = [
  ...COMMON_SHOPPING_ITEMS,
  // Additional common Spanish words
  "botella", "caja", "paquete", "kilo", "litro", "medio", "docena",
  "unidad", "bolsa", "grande", "pequeño", "mediano"
];

// Common misspellings map
export const COMMON_MISSPELLINGS_MAP: Record<string, string> = {
  "aseite": "aceite",
  "aseituna": "aceituna",
  "ajo": "ajo",
  "aroz": "arroz",
  "atunn": "atún",
  "azucar": "azúcar",
  "bananna": "banana",
  "carne": "carne",
  "kafe": "café",
  "zevolla": "cebolla",
  "servesa": "cerveza",
  "champu": "champú",
  "chololate": "chocolate",
  "deterjente": "detergente",
  "guevo": "huevo",
  "guebos": "huevos",
  "jabon": "jabón",
  "jamon": "jamón",
  "leche": "leche",
  "lechuga": "lechuga",
  "limon": "limón",
  "mansana": "manzana",
  "naranga": "naranja",
  "pan": "pan",
  "papas": "patatas",
  "peskado": "pescado",
  "platano": "plátano",
  "poyo": "pollo",
  "keso": "queso",
  "tomatte": "tomate",
  "uba": "uva",
  "berdura": "verdura",
  "bino": "vino",
  "yogurt": "yogur"
};
